---
- name: sites | Manage Site(s)
  nbox_site:
    asn: "{{ item['asn']|default(omit) }}"
    comments: "{{ item['comments']|default(omit) }}"
    contact_email: "{{ item['contact_email']|default(omit) }}"
    contact_name: "{{ item['contact_name']|default(omit) }}"
    contact_phone: "{{ item['contact_phone']|default(omit) }}"
    custom_fields: "{{ item['custom_fields']|default(omit) }}"
    description: "{{ item['description']|default(omit) }}"
    facility: "{{ item['facility']|default(omit) }}"
    latitude: "{{ item['latitude']|default(omit) }}"
    longitude: "{{ item['longitude']|default(omit) }}"
    name: "{{ item['name'] }}"
    netbox_token: "{{ netbox_token }}"
    netbox_url: "{{ netbox_url }}"
    physical_address: "{{ item['physical_address']|default(omit) }}"
    region: "{{ item['region']|default(omit) }}"
    shipping_address: "{{ item['shipping_address']|default(omit) }}"
    state: "{{ item['state']|default('present') }}"
    status: "{{ item['status'] }}"
    tags: "{{ item['tags']|default(omit) }}"
    tenant: "{{ item['tenant']|default(omit) }}"
    time_zone: "{{ item['time_zone']|default(omit) }}"
  loop: "{{ netbox_sites }}"
