---
- name: vlan | Manage VLAN(s)
  nbox_vlan:
    description: "{{ item.description|default(omit) }}"
    group: "{{ item.group|default(omit) }}"
    name: "{{ item.name }}"
    netbox_token: "{{ netbox_token }}"
    netbox_url: "{{ netbox_url }}"
    role: "{{ item.role|default(omit) }}"
    site: "{{ item.site|default(omit) }}"
    status: "{{ item.status }}"
    state: "{{ item.state|default('present') }}"
    tags: "{{ item.tags|default(omit) }}"
    tenant: "{{ item.tenant|default(omit) }}"
    vid: "{{ item.vid }}"
  loop: "{{ netbox_vlans }}"
  delegate_to: localhost
  retries: 5
