---
dependency:
  name: galaxy
  enabled: true
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8 --exclude=venv
platforms:
  - name: debian8
    image: jrei/systemd-debian:8
    privileged: true
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
verifier:
  name: ansible
