---
dependency:
  name: galaxy
  enabled: true
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8 --exclude=venv
platforms:
  - name: ubuntu1604
    image: jrei/systemd-ubuntu:16.04
    privileged: true
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    exposed_ports:
      - 80/tcp
    published_ports:
      - 0.0.0.0:8080:80/tcp
provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
verifier:
  name: ansible
